name: Mine Cryptocurrency Docker

on:
  push:
    branches:
      - main

jobs:
  mine:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t xmrig-miner -f ./dockerfiles/xmrig.Dockerfile .

      - name: Run XMRig in Docker
        run: |
          docker run xmrig-miner
